### PR TITLE
[rest] release sockets in destructors

### LINKED ISSUE #817: [github-actions] meshcop test fails intermittently
[logs_7747.zip](https://github.com/openthread/ot-br-posix/files/6389182/logs_7747.zip)

```
otbr-agent[19504]: Set state callback: OK
otbr-agent[19504]: stop Thread Border Agent
otbr-agent[19504]: Initialize OpenThread Border Router Agent: OK
otbr-agent[19504]: dbus error (null): (null)
otbr-agent[19504]: InitializeListenFd error bind : Address already in use
otbr-agent[19504]: FAILED InitializeListenFd:158 - otbr rest server init error
+ pidof otbr-agent
+ die 'AGENT: failed to start'
+ exit_message='AGENT: failed to start'
+ echo ' *** ERROR: AGENT: failed to start'
 *** ERROR: AGENT: failed to start
+ exit 1
+ test_teardown
+ readonly EXIT_CODE=1
+ EXIT_CODE=1
+ write_syslog 'EXIT 1 - output logs'
+ logger -s -p syslog.alert 'OPENTHREAD_TEST: EXIT 1 - output logs'
<41>Apr 28 04:21:27 runner: OPENTHREAD_TEST: EXIT 1 - output logs
+ sudo pkill -f otbr-agent
+ sudo pkill -f otbr-web
+ sudo pkill -f commissioner-cli
+ sudo pkill -f ot-cli-ftd
+ wait
+ [[ 1 != 1 ]]
+ echo 'EXIT 1: MESSAGE: AGENT: failed to start'
EXIT 1: MESSAGE: AGENT: failed to start
+ exit 1
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by wgtdkp**
Resolves #817

### CODE REVIEW

File: src/rest/rest_web_server.cpp [hunk 1]
```diff
@@ -139,7 +147,7 @@ void RestWebServer::InitializeListenFd(void)
     mListenFd = SocketWithCloseExec(AF_INET, SOCK_STREAM, 0, kSocketNonBlock);
     VerifyOrExit(mListenFd != -1, err = errno, error = OTBR_ERROR_REST, errorMessage = "socket");
 
-    ret = setsockopt(mListenFd, SOL_SOCKET, SO_REUSEADDR, reinterpret_cast<char *>(&optval), sizeof(optval));
+    ret = setsockopt(mListenFd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, reinterpret_cast<char *>(&optval), sizeof(optval));
```
Comment (simonlingoogle) [inline src/rest/rest_web_server.cpp:150]: Why is `SO_REUSEPORT` necessary?

Comment (wgtdkp) [reply src/rest/rest_web_server.cpp]: I was just trying different options to see what happens.

File: tests/scripts/meshcop [hunk 2]
```diff
@@ -269,6 +269,7 @@ ba_start()
 
     write_syslog "AGENT: kill old"
     sudo killall "${OTBR_AGENT}" || true
+    sleep 5
```
Comment (wgtdkp) [inline tests/scripts/meshcop:272]: It is actually this line that fixes the CI failure. The problem is that we starts the otbr-agent and immediately after killing it, leaving the TCP socket still running in the background. `SO_REUSEDRR` doesn't always solve this issue because otbr-agent is re-started too quickly before the socket going to the `TIME_WAIT` status.

Sleeping for 5 seconds is for the socket transits to the `TIME_WAIT` status or shutdown completely.

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Review by bukepo — APPROVED** [review]

**Review by jwhui — APPROVED** [review]
